config/routes.rb
require 'sidekiq/web'

Fraefel::Application.routes.draw do

  devise_for :users

  mount Sidekiq::Web, at: '/sidekiq'

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :articles do
    collection do
      get 'search_for'
      get 'get_results_for'
      get 'edit_multiple'
      put 'update_multiple'
      get 'calculate_difference_for'
      get 'export'
    end
  end

  namespace :api do
    resources :purchase_positions
  end

  resources :pallet_types

  resources :queues, :only => [:destroy]
  
  resources :users

  resources :addresses

  resources :pdf_reports

  resources :departments

  resources :shifting_reasons

  resources :shipping_routes

  resources :time_shiftings

  resource :dashboard, :only => [:show]

  resources :microsoft_databases

  resources :roles

  resources :categories

  resources :statuses

  resources :customers

  resources :export_declarations

  resources :pallet_purchase_position_assignments do
    collection do
      get :new_multiple
      post :create_multiple
      delete :destroy_multiple
    end
  end

  resources :versions, :only => [:update, :destroy]

  resources :baan_imports do
    member do
      get 'import'
    end
    collection do
      delete 'destroy_all'
    end
  end

  resources :purchase_positions do
    collection do
      get 'search_for'
      get 'index_beta'
    end
  end

  resources :purchase_orders do
    resources :time_shiftings
    member do
      get 'print_pallets'
    end
    collection do
      get 'import_orders'
      get 'search_for'
      delete 'destroy_multiple'
      get 'index_beta'
    end
  end

  resources :pallets do
    member do
      delete 'remove_positions'
      get 'ajax_show'
    end
    collection do
      post 'assign_positions'
      delete 'delete_empty'
      get 'search_for'
    end
  end

  resources :cargo_lists do
    collection do
      post 'assign_pallets'
      post 'remove_pallets'
      get 'search_for'
    end
    member do
      put 'recalculate'
      get 'print_pallets'
      get 'collective_invoice'
      get 'print_lebert'
      get 'controll_invoice'
    end
  end

  resources :delivery_rejections do
    member do
      post 'assign_positions'
      delete 'remove_positions'
    end
    collection do
      post 'search'
    end
  end

  resources :purchase_order_pallet_assignments

  resources :stocktakings

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "dashboards#show"

end

app/models/time_shifting.rb
# encoding: utf-8
class TimeShifting < ActiveRecord::Base
  attr_accessor :articles
  
  has_many :purchase_position_time_shifting_assignments, :dependent => :destroy
  has_many :purchase_positions, :class_name => "PurchasePosition", :through => :purchase_position_time_shifting_assignments
  has_many :comments, :as => :commentable
  
  has_many :shifting_reason_time_shifting_assignments, :dependent => :destroy
  has_many :shifting_reasons, :class_name => "ShiftingReason", :through => :shifting_reason_time_shifting_assignments
  
  has_many :article_position_time_shifting_assignments, :dependent => :destroy
  has_many :article_positions, :class_name => "ArticlePosition", :through => :article_position_time_shifting_assignments
  
  has_many :department_time_shifting_assignments, :dependent => :destroy
  has_many :departments, :class_name => "Department", :through => :department_time_shifting_assignments
  
  belongs_to :department, :class_name => "Department", :foreign_key => "department_id"
  
  belongs_to :purchase_order, :class_name => "PurchaseOrder", :foreign_key => "purchase_order_id", :primary_key => "baan_id"
  
  accepts_nested_attributes_for :purchase_position_time_shifting_assignments
  accepts_nested_attributes_for :shifting_reason_time_shifting_assignments
  accepts_nested_attributes_for :comments, :reject_if => proc { |obj| obj['content'].blank? }
  accepts_nested_attributes_for :article_positions
  accepts_nested_attributes_for :article_position_time_shifting_assignments
  accepts_nested_attributes_for :department_time_shifting_assignments, :reject_if => proc { |obj| obj['department_id'].blank? }
  accepts_nested_attributes_for :purchase_order
  
  validates_presence_of :department_id, :on => :create, :message => "muss ausgewählt werden"
  validates_presence_of :shifting_reasons, :on => :create, :message => "muss ausgewählt werden"
  validates_presence_of :lt_date, :on => :update, :message => "muss gesetzt werden", :if => "closed"
  #validates_presence_of :purchase_positions
  
  def self.clean_up
    where(:closed => false).each do |ts|
      @considered = ts.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments)
      @production_completed = ts.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).where("purchase_positions.production_status = 1").includes(:purchase_position_time_shifting_assignments)
      if @considered.present?
        if @considered.count == @production_completed.count
          ts.update_attribute("closed", true)
          ts.comments.create(:content => "Closed by system", :created_by => User.first.id)
          @considered.update_all(:priority_level => 2)
          if ts.purchase_order.present?
            ts.purchase_order.update_attribute("priority_level", 2)
          end
          if ts.lt_date.present?
            @considered.each do |pu_po|
              pu_po.delivery_dates.last.try(:date_of_delivery) != pu_po.delivery_date.to_date ? pu_po.delivery_dates.create(:date_of_delivery => ts.lt_date) : nil
              pu_po.update_attribute(:delivery_date, ts.lt_date)
            end
            if ts.purchase_order.present?
              ts.purchase_order.update_attribute("delivery_date", ts.lt_date)
            end
          end
        
        end
      end
      
    end
  end
  
end

app/controllers/time_shiftings_controller.rb
# encoding: utf-8

class TimeShiftingsController < FraefelController
  before_filter :collect_departments, :only => :index
  before_filter :collect_shifting_reasons, :only => :index

  def show
    @time_shifting = TimeShifting.where(:id => params[:id])
    @purchase_positions = @time_shifting.first.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments)
    @article_positions = @time_shifting.first.article_positions.order("created_at DESC")
    @purchase_order = PurchaseOrder.where(:baan_id => @time_shifting.first.purchase_order_id)
    @comments = @time_shifting.first.comments.order("created_at DESC")
    @departments = @time_shifting.first.department_time_shifting_assignments.order("department_time_shifting_assignments.created_at DESC").includes(:department, :creator)

    respond_to do |format|
      format.html
      format.pdf do
        render(
          :pdf => "fraefel_app-#{Date.today}",
          :wkhtmltopdf => '/usr/bin/wkhtmltopdf',
          :layout => 'pdf.html',
          :show_as_html => params[:debug].present?,
          :orientation => 'Portrait',
          :encoding => 'UTF-8',
          :footer => {
            :left => "#{Time.now.to_formatted_s(:swiss_date)}",
            :right => "Seite [page] / [topage]",
            :line => false
          }
        )
      end
    end

  end

  def index
    # @search = TimeShifting.includes(:purchase_order).order("time_shiftings.id DESC, time_shiftings.lt_date ASC, time_shiftings.purchase_order_id ASC").search(params[:search] || {:closed_equals => "false"})
    @search = TimeShifting.order("time_shiftings.id DESC, time_shiftings.lt_date ASC").search(params[:q] || {:closed_eq => "false"})

    @time_shiftings = @search.result

    #@requested_department_id = params["search"]["department_id_equals"] if params[:search]


    respond_to do |format|
      format.html
      format.pdf do
        if params[:pdf_type].present? && params[:pdf_type] == "article_positions"
          @time_shiftings = @time_shiftings.where("article_positions.id IS NOT NULL").includes(:article_positions)
        end
        render(
          :pdf => "Kein Titel-#{Date.today}",
          :wkhtmltopdf => '/usr/bin/wkhtmltopdf',
          :layout => 'pdf.html',
          :show_as_html => params[:debug].present?,
          :orientation => 'Landscape',
          :encoding => 'UTF-8',
          :footer => {
            :left => "#{Time.now.to_formatted_s(:swiss_date)}",
            :right => "Seite [page] / [topage]",
            :line => false
          }
        )
      end
    end

  end

  def new
    @time_shifting = TimeShifting.new(params[:time_shifting])
    @departments = Department.order("departments.title ASC")
    @purchase_order = (params[:time_shifting].present? && params[:time_shifting][:purchase_order_id].present?) ? PurchaseOrder.where(:baan_id => params[:time_shifting][:purchase_order_id]) : nil

    if @purchase_order.present?
       @purchase_positions = @purchase_order.first.purchase_positions
       @shifting_reasons = ShiftingReason.where("departments.id IN(?)", User.current.departments(&:id)).includes(:departments)

       @time_shifting.comments.build
       #@time_shifting.shifting_reason_time_shifting_assignments.build

       @purchase_positions.each do |purchase_position|
         @time_shifting.purchase_position_time_shifting_assignments.build(:purchase_position_id => purchase_position.id)
      end
    end

  end

  def create
    @time_shifting = TimeShifting.new(params[:time_shifting])
    @departments = Department.order("departments.title ASC")
    @purchase_order = PurchaseOrder.where(:baan_id => @time_shifting.purchase_order_id)
    @purchase_positions = @purchase_order.first.purchase_positions
    @shifting_reasons = ShiftingReason.where("departments.id IN(?)", User.current.departments(&:id)).includes(:departments)


    @time_shifting.comments.build if @time_shifting.comments.empty?

    if @time_shifting.save
      @time_shifting.departments << @time_shifting.department
      PurchaseOrder.where(:baan_id => @time_shifting.purchase_order_id).first.update_attribute("priority_level", 0)
      ### Move this away from here....
      @time_shifting.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments).update_all(:priority_level => 0)
      @time_shifting.purchase_positions.each do |purchase_position|
        purchase_position.patch_html_content
      end
      @time_shifting.purchase_order.patch_btn_cat_a
      redirect_to(time_shiftings_path)
    else
      render 'new'
    end
  end

  def edit
    @time_shifting = TimeShifting.where(:id => params[:id])
    # @time_shifting.first.department = nil
    @purchase_positions = @time_shifting.first.purchase_position_time_shifting_assignments.includes(:purchase_position)
    @shifting_reasons = ShiftingReason.where("departments.id IN(?)", User.current.departments(&:id)).includes(:departments)
    @departments = Department.order("departments.title ASC")
    @purchase_order = PurchaseOrder.where(:baan_id => @time_shifting.first.purchase_order_id)
    @time_shifting.first.comments.build
    @time_shifting.first.department_time_shifting_assignments.build
    #@time_shifting.first.shifting_reason_time_shifting_assignments.build
  end

  def update
    @time_shifting = TimeShifting.where(:id => params[:id])
    @purchase_order = PurchaseOrder.where(:baan_id => @time_shifting.first.purchase_order_id)
    @purchase_positions = @time_shifting.first.purchase_position_time_shifting_assignments.includes(:purchase_position)
    @departments = Department.order("departments.title ASC")

    if @time_shifting.first.update_attributes(params[:time_shifting])
      if @time_shifting.first.department_id != @time_shifting.first.departments.last.id
        @time_shifting.first.departments << @time_shifting.first.department
      end
      ### Move this logic to a filter!!
      if @time_shifting.first.department_time_shifting_assignments.where("completed_at IS NULL").count > 1
        @time_shifting.first.department_time_shifting_assignments.where("completed_at IS NULL").first.update_attribute("completed_at", Time.now)
      end
      if @time_shifting.first.closed && @time_shifting.first.lt_date.present?
        @purchase_order.first.priority_level = 2
        @purchase_order.first.save
        @time_shifting.first.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments).update_all(:priority_level => 2)
      end
      if @time_shifting.first.lt_date.present?
        @time_shifting.first.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments).each do |purchase_position|
          purchase_position.delivery_dates.last.try(:date_of_delivery) != purchase_position.delivery_date.to_date ? purchase_position.delivery_dates.create(:date_of_delivery => @time_shifting.first.lt_date) : nil
          purchase_position.update_attribute(:delivery_date, @time_shifting.first.lt_date)
        end
        @purchase_order.first.update_attribute("delivery_date", @time_shifting.first.lt_date)
        @time_shifting.first.purchase_positions.each do |purchase_position|
          purchase_position.patch_html_content
        end
      end

      redirect_to(@time_shifting.first)
    else
      render 'edit'
    end
  end

  private

  def collect_departments
    closed_condition = false
    if params[:search].present?
      if params[:search][:closed_equals] == "true"
        closed_condition = true
      end
    end
    @departments = Department.includes(:time_shiftings).where("time_shiftings.id IS NOT NULL").where("time_shiftings.closed = ?", closed_condition).order("departments.title ASC")
  end

  def collect_shifting_reasons
    closed_condition = false
    if params[:search].present?
      if params[:search][:closed_equals] == "true"
        closed_condition = true
      end
    end
    @shifting_reasons = ShiftingReason.includes(:time_shiftings).where("time_shiftings.id IS NOT NULL").where("time_shiftings.closed = ?", closed_condition).order("shifting_reasons.title ASC")
  end

end

app/helpers/time_shiftings_helper.rb
module TimeShiftingsHelper
end

app/views/time_shiftings/_article_position_fields.html.erb
<%= f.input :baan_id, :label => "Artikel Code", :hint => "Füge einen Artikel Code hinzu. Wert wird nicht auf gültigkeit überprüft." %>

app/views/time_shiftings/_article_position_time_shifting_assignment_fields.html.erb
<% f.object.article_position.present? ? nil : f.object.build_article_position %>
<% f.object.comments.present? ? nil : f.object.comments.build %>

<fieldset>
  <legend>Artikel Code <small><a href="#">entfernen</a></small></legend>
<%= f.simple_fields_for :article_position do |builder| %>
  <%= render 'article_position_fields', :f => builder %>
<% end %>

<%= f.input :purchase_positions_collection, :as => :string, :label => "Betroffene VK-Pos", :hint => "Trage die Betroffenen VK-Positionen ein. Alle möglichen VK-Pos sind in der Tabelle oben ersichtlich." %>
<%= f.input :order_number, :hint => "Bestellnummer" %>
<%= f.input :confirmed_date, :as => :string, :input_html => { :class => 'date_picker' } %>

  <fieldset>
    <legend>Artikel Code Kommentar</legend>
    <%= f.simple_fields_for :comments do |builder| %>
      <%= builder.input :content, :as => :string, :label => false, :hint => "Hast du Informationen zu diesem Artikel? Trage diese hier ein." %>
    <% end %>
  </fieldset>
</fieldset>

app/views/time_shiftings/_department_time_shifting_assignment_fields.html.erb
<% if f.object.new_record? %>
  <%= f.input :department_id, :collection => @departments, :hint => "Wähle die nächste betroffene Abteilung" %>
<% end %>

app/views/time_shiftings/_edit_form.html.erb
<%= simple_form_for(@time_shifting.first, :html => {:class => "form-horizontal"}) do |f| %>

  <div class="tab-content">
    <%= content_tag :div, :id => "tab1", :class => ["tab-pane", params[:tab].present? ? nil : "active"].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_1', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab2", :class => ["tab-pane", params[:tab] == "tab2" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_2', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab3", :class => ["tab-pane", params[:tab] == "tab3" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_3', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab4", :class => ["tab-pane", params[:tab] == "tab4" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_4', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab5", :class => ["tab-pane", params[:tab] == "tab5" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_5', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab6", :class => ["tab-pane", params[:tab] == "tab6" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_6', :f => f %>
    <% end %>
    
    <%= content_tag :div, :id => "tab7", :class => ["tab-pane", params[:tab] == "tab7" ? "active" : nil].compact.join(" ") do %>
      <%= render 'time_shiftings/tabs/edit/tab_7', :f => f %>
    <% end %>
  </div>
  
<% end %>
<script type="text/javascript" charset="utf-8">
  $("form").on("click", ".add_fields", function(event){
    var time = new Date().getTime();
    var regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    event.preventDefault();
  });
</script>

app/views/time_shiftings/_form.html.erb
<%= simple_form_for(@purchase_order.present? ? [@purchase_order.first, @time_shifting] : @time_shifting, :url => @purchase_order.present? ? time_shiftings_path : new_time_shifting_path, :html => {:method => @purchase_order.present? ? :post : :get}) do |f| %>

  <div style="padding-bottom: 9px; border-bottom: 1px solid #ddd;" class="tab-content">
    <div id="tab1" class="tab-pane active">
      <%= render 'time_shiftings/tabs/new/tab_1', :f => f %>
    </div>
  
    <% unless @purchase_order.blank? %>
      <div id="tab2" class="tab-pane">
        <%= render 'time_shiftings/tabs/new/tab_2', :f => f %>
      </div>
      <div id="tab3" class="tab-pane">
        <%= render 'time_shiftings/tabs/new/tab_3', :f => f %>
      </div>
      <div id="tab4" class="tab-pane">
        <%= render 'time_shiftings/tabs/new/tab_4', :f => f %>
      </div>
      <div id="tab5" class="tab-pane">
        <%= render 'time_shiftings/tabs/new/tab_5', :f => f %>
      </div>
    <% end %>
  </div>
  
<% end %>
<script type="text/javascript" charset="utf-8">
  $("form").on("click", ".add_fields", function(event){
    var time = new Date().getTime();
    var regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    event.preventDefault();
  });
</script>

app/views/time_shiftings/_purchase_position_time_shifting_assignment_fields.html.erb
<tr>
  <td><%= f.object.purchase_position.delivery_date.to_date.to_formatted_s(:swiss_date) %></td>
  <td><%= @purchase_order.first.shipping_route.name %></td>
  <td><span class="btn btn-mini disabled btn-<%= f.object.purchase_position.production_status %><%= f.object.purchase_position.stock_status %>"><%= f.object.purchase_position.baan_id %></span></td>
  <td><%= f.object.purchase_position.article_number %></td>
  <td><%= f.object.purchase_position.quantity %></td>
  <td><%= f.object.purchase_position.article %></td>
  <td><%= f.object.purchase_position.product_line %></td>
  <td><%= f.object.purchase_position.commodity_code.content %></td>
  <td><%= f.object.purchase_position.storage_location %></td>
  <td>
    <%= f.input(:purchase_position_id, :as => :hidden, :label => false) %>
    <%= f.input :considered, :as => :select, :label => false, :include_blank => false %>
  </td>
</tr>

app/views/time_shiftings/_shifting_reason_time_shifting_assignment_fields.html.erb
<%= f.input :shifting_reason_id, :as => :select, :collection => @shifting_reasons, :label => "Verzugsgrund", :hint => "Wähle den Grund der Verschiebung" %>

app/views/time_shiftings/edit.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li><a href="<%= time_shiftings_path %>">Terminverschiebungen</a> <span class="divider">/</span></li>
    <li><a href="<%= time_shifting_path(@time_shifting.first.id) %>"><%= @time_shifting.first.id %></a> <span class="divider">/</span></li>
    <li class="active">Edit</li>
  </ul>
<% end %>

<div class="page-header">
  <h1>Bearbeite Terminverschiebung</h1>
</div>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <%= content_tag :li, :class => params[:tab].present? ? nil : "active" do %>
      <a data-toggle="tab" href="#tab1">VK-Auftrag</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab2" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab2">VK-Pos</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab3" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab3">Beschaffung</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab4" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab4">Abteilung</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab5" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab5">Bemerkung</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab6" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab6">Verschiebung</a>
    <% end %>
    <%= content_tag :li, :class => params[:tab] == "tab7" ? "active" : nil do %>
      <a data-toggle="tab" href="#tab7">Abschliessen</a>
    <% end %>
  </ul>
  <%= render 'edit_form' %>
</div>

<script type="text/javascript" charset="utf-8">
  $('a[data-toggle="tab-changer"]').click(function(event) {
    event.preventDefault();
    $('.nav-tabs a[href="' + $(this).attr("href") + '"]').tab("show")
  });
</script>

app/views/time_shiftings/index.html.erb
<%= render("time_shiftings/partials/index/modal/filter") %>
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li class="active">Terminverschiebungen</li>
  </ul>
<% end %>

<div class="page-header">
    <h1 class="pull-left">Terminverschiebungen</h1>
    <div class="btn-toolbar pull-right">
      <div class="btn-group">
        <a class="btn btn-primary" href="<%= new_time_shifting_path() %>"><i class="icon-plus-sign icon-white"></i> Neue Terminverschiebung</a>
      </div>
      
      <div class="btn-group">
        <a href="<%= url_for(params.merge(:format => :pdf)) %>" class="btn btn-primary"><i class="icon-print icon-white"></i> Drucke PDF</a>
        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="<%= url_for(params.merge(:format => :pdf, :pdf_type => "article_positions")) %>"><i class="icon-print"></i> Drucke PDF Beschaffung</a>
          </li>
        </ul>
      </div>
      
      
      <div class="btn-group">
        <a data-toggle="modal" href="#filter" class="btn"><i class="icon-filter"></i> Filter</a>
      </div>
      
    </div>
    <div class="clear"></div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>VK-Auftrag</th>
      <th>Teillieferung?</th>
      <th>LT Neu</th>
      <th>anz. VK-Pos</th>
      <th>Grund</th>
      <th>Abteilung</th>
      <th>Editiert am</th>
    </tr>
  </thead>
  <tbody>
    <% if @time_shiftings.present? %>
      <% @time_shiftings.each do |time_shifting| %>
        <tr>
          <td><%= link_to(time_shifting.id, time_shifting) %></td>
          <td><%= time_shifting.purchase_order_id %></td>
          <td><%= time_shifting.simple %></td>
          <td><%= time_shifting.lt_date.to_formatted_s(:swiss_date) if time_shifting.lt_date.present? %></td>
          <td><%= time_shifting.purchase_positions.where("purchase_position_time_shifting_assignments.considered" => true).includes(:purchase_position_time_shifting_assignments).count %></td>
          <td><%= time_shifting.shifting_reasons.collect(&:title) %></td>
          <td><%= "#{time_shifting.departments.last.try(:title)} ...seit #{distance_of_time_in_words(time_shifting.department_time_shifting_assignments.last.created_at, Time.now)}" %></td>
          <td><%= time_shifting.updated_at.to_formatted_s(:swiss_date) %></td>
        </tr>
      <% end %>
    <% else %>
      <tr><td>Keine aktiven Verschiebungen vorhanden.</td></tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
</table>

app/views/time_shiftings/show.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li><a href="<%= time_shiftings_path %>">Terminverschiebungen</a> <span class="divider">/</span></li>
    <li class="active"><%= @time_shifting.first.id %></li>
  </ul>
<% end %>

<div class="page-header">
    <h1 class="pull-left">Termin Verschiebung NR#<%= @time_shifting.first.id %></h1>
    <div class="btn-toolbar pull-right">
      <div class="btn-group">
        <a class="btn btn-primary" href="<%= time_shifting_path(@time_shifting.first, :format => :pdf) %>"><i class="icon-print icon-white"></i> PDF</a>
      </div>
      
      <div class="btn-group">
        <a class="btn btn-primary" href="<%= edit_time_shifting_path(@time_shifting.first) %>"><i class="icon-pencil icon-white"></i> Edit</a>
      </div>
      <div class="btn-group">
        <a class="btn btn-warning" href="<%= edit_time_shifting_path(@time_shifting.first, :tab => "tab7") %>"><i class="icon-off icon-white"></i> Abschliessen</a>
      </div>
    </div>
    <div class="clear"></div>
</div>

<div class="row">
  <div class="tabbable tabs-left" style="padding: 8px 0;">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#tab1" data-toggle="tab">Allgemein</a>
      </li>
      <li>
        <a href="#tab2" data-toggle="tab">Abteilungen</a>
      </li>
      <li>
        <a href="#tab3" data-toggle="tab">Beschaffung <span class="badge badge-info"><%= @article_positions.count %></span></a>
      </li>
      <li>
        <a href="#tab4" data-toggle="tab">VK-Positionen <span class="badge badge-info"><%= @purchase_positions.count %></span></a>
      </li>
      <li>
        <a href="#tab5" data-toggle="tab">Nachrichten <span class="badge badge-info"><%= @comments.count %></span></a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="tab1">
        <%= render 'time_shiftings/tabs/show/tab_1' %>
      </div>
      <div class="tab-pane" id="tab2">
        <%= render 'time_shiftings/tabs/show/tab_2' %>
      </div>
      <div class="tab-pane" id="tab3">
        <%= render 'time_shiftings/tabs/show/tab_3' %>
      </div>
      <div class="tab-pane" id="tab4">
        <%= render 'time_shiftings/tabs/show/tab_4' %>
      </div>
      <div class="tab-pane" id="tab5">
        <%= render 'time_shiftings/tabs/show/tab_5' %>
      </div>
    </div>
  </div>
</div>