config/routes.rb
require 'sidekiq/web'

Fraefel::Application.routes.draw do

  devise_for :users

  mount Sidekiq::Web, at: '/sidekiq'

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :articles do
    collection do
      get 'search_for'
      get 'get_results_for'
      get 'edit_multiple'
      put 'update_multiple'
      get 'calculate_difference_for'
      get 'export'
    end
  end

  namespace :api do
    resources :purchase_positions
  end

  resources :pallet_types

  resources :queues, :only => [:destroy]
  
  resources :users

  resources :addresses

  resources :pdf_reports

  resources :departments

  resources :shifting_reasons

  resources :shipping_routes

  resources :time_shiftings

  resource :dashboard, :only => [:show]

  resources :microsoft_databases

  resources :roles

  resources :categories

  resources :statuses

  resources :customers

  resources :export_declarations

  resources :pallet_purchase_position_assignments do
    collection do
      get :new_multiple
      post :create_multiple
      delete :destroy_multiple
    end
  end

  resources :versions, :only => [:update, :destroy]

  resources :baan_imports do
    member do
      get 'import'
    end
    collection do
      delete 'destroy_all'
    end
  end

  resources :purchase_positions do
    collection do
      get 'search_for'
      get 'index_beta'
    end
  end

  resources :purchase_orders do
    resources :time_shiftings
    member do
      get 'print_pallets'
    end
    collection do
      get 'import_orders'
      get 'search_for'
      delete 'destroy_multiple'
      get 'index_beta'
    end
  end

  resources :pallets do
    member do
      delete 'remove_positions'
      get 'ajax_show'
    end
    collection do
      post 'assign_positions'
      delete 'delete_empty'
      get 'search_for'
    end
  end

  resources :cargo_lists do
    collection do
      post 'assign_pallets'
      post 'remove_pallets'
      get 'search_for'
    end
    member do
      put 'recalculate'
      get 'print_pallets'
      get 'collective_invoice'
      get 'print_lebert'
      get 'controll_invoice'
    end
  end

  resources :delivery_rejections do
    member do
      post 'assign_positions'
      delete 'remove_positions'
    end
    collection do
      post 'search'
    end
  end

  resources :purchase_order_pallet_assignments

  resources :stocktakings

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "dashboards#show"

end

app/models/shifting_reason.rb
class ShiftingReason < ActiveRecord::Base
  has_many :department_shifting_reason_assignments
  has_many :departments, :class_name => "Department", :through => :department_shifting_reason_assignments
  
  has_many :shifting_reason_time_shifting_assignments
  has_many :time_shiftings, :class_name => "TimeShifting", :through => :shifting_reason_time_shifting_assignments
  
end

app/controllers/shifting_reasons_controller.rb
# encoding: utf-8

class ShiftingReasonsController < FraefelController
  def index
    @shifting_reasons = ShiftingReason.order("shifting_reasons.title ASC")
  end

  def new
    @shifting_reason = ShiftingReason.new
  end

  def create
    @shifting_reason = ShiftingReason.new(params[:shifting_reason])

    if @shifting_reason.save
      redirect_to(shifting_reasons_path)
    end
  end

  def edit
    @shifting_reason = ShiftingReason.where(:id => params[:id]).first
  end

  def update
    @shifting_reason = ShiftingReason.where(:id => params[:id])

    if @shifting_reason.first.update_attributes(params[:shifting_reason])
      redirect_to(shifting_reasons_path)
    end
  end

end

app/helpers/shifting_reasons_helper.rb
module ShiftingReasonsHelper
end

app/views/shifting_reasons/_form.html.erb
<%= simple_form_for @shifting_reason, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <%= f.input :title, :label => "Verschiebungsgrund" %>
    <%= f.association :departments, :label => "Abteilung", :as => :check_boxes %>
    
    <div class="form-actions">
      <%= f.submit "Speichern", :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', shifting_reasons_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/shifting_reasons/edit.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li class="active">Verschiebungsgrund</li>
  </ul>
<% end %>

<div class="page-header">
    <h1 class="pull-left">Verschiebungsgrund bearbeiten</h1>
    <div class="clear"></div>
</div>

<%= render 'form' %>

app/views/shifting_reasons/index.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li class="active">Verschiebungsgrund</li>
  </ul>
<% end %>

<div class="page-header">
    <h1 class="pull-left">Verschiebungsgrund</h1>
    <div class="btn-toolbar pull-right">
    
      <div class="btn-group">
        <a class="btn btn-primary" href="<%= new_shifting_reason_path() %>">Neuer Verschiebungsgrund</a>
      </div>
      
    </div>
    <div class="clear"></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Verschiebungsgrund</th>
      <th>anw. durch</th>
      <th>Erstellt durch</th>
      <th>Erstellt am</th>
    </tr>
  </thead>
  <tbody>
    <% @shifting_reasons.each do |shifting_reason| %>
      <tr>
        <td><%= link_to(shifting_reason.id, edit_shifting_reason_path(shifting_reason)) %></td>
        <td><%= shifting_reason.title %></td>
        <td><%= shifting_reason.departments.collect(&:title) %></td>
        <td><%= shifting_reason.created_by %></td>
        <td><%= shifting_reason.created_at.to_formatted_s(:swiss_date) %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tfoot>
</table>

app/views/shifting_reasons/new.html.erb
<% content_for :breadcrumb do %>
  <ul class="breadcrumb">
    <li class="active">Verschiebungsgrund</li>
  </ul>
<% end %>

<div class="page-header">
    <h1 class="pull-left">Erfasse neuen Verschiebungsgrund</h1>
    <div class="clear"></div>
</div>

<%= render 'form' %>